# ---Anki---
# Leave `target deck` empty if you don't want to send cards to Anki via Anki Connect API.
# Then, cards will only be exported as a text file.
#target deck: IT
target deck: IT

# ---Files---
# Source material for regular cards (non-code, just text that will be split into sentences)
input file: input.txt

# Source material for code-based cards (handled differently)
code input file: code_input.txt

# File for new cards (in text format, can be imported to Anki)
cards output file: new_cards.txt

# Backup file for previously generated new cards (in text format, can be imported to Anki)
cards output backup file: new_cards_backup.txt