GAP_SPECIAL_CASES = {
    'absolute': '_____(absolute or relative?)',
    'always': '_____(always or never?)',
    'after': '_____(after or before?)',
    'are no': '_____(are or are no?)',
    'are not': '_____(are or aren\'t?)',
    'are': '_____(are or aren\'t?)',
    'aren\'t': '_____(are or aren\'t?)',
    'avoid': '_____(avoid or embrace?)',
    'bad': '_____(good or bad?)',
    'before': '_____(after or before?)',
    'beneficial': '_____(beneficial or harmful?)',
    'big': '_____(size)',
    'can': '_____(can or can\'t?)',
    'can\'t': '_____(can or can\'t?)',
    'cannot': '_____(can or can\'t?)',
    'decrease': '_____(increase or decrease?)',
    'decreases': '_____(increases or decreases?)',
    'do not have to': '_____(must or don\'t have to?)',
    'do not have': '_____(have or don\'t have?)',
    'do not': '_____(do or don\'t?)',
    'do': '_____(do or don\'t?)',
    'does not have to': '_____(must or doesn\'t have to?)',
    'does not have': '_____(has or doesn\'t have?)',
    'does not': '_____(does or doesn\'t?)',
    'does': '_____(does or doesn\'t?)',
    'doesn\'t have to': '_____(must or doesn\'t have to?)',
    'doesn\'t have': '_____(has or doesn\'t have?)',
    'doesn\'t need': '_____(need or doesn\'t need?)',
    'doesn\'t': '_____(does or doesn\'t?)',
    'don\'t have to': '_____(must or don\'t have to?)',
    'don\'t have': '_____(have or don\'t have?)',
    'don\'t need': '_____(need or don\'t need?)',
    'don\'t': '_____(do or don\'t?)',
    'early': '_____(early or late?)',
    'earlier': '_____(earlier or later?)',
    'embrace': '_____(avoid or embrace?)',
    'fast': '_____(fast or slow?)',
    'faster': '_____(faster or slower?)',
    'good': '_____(good or bad?)',
    'graduate': '_____(graduate or immediate?)',
    'graduately': '_____(graduately or immediately?)',
    'happy': '_____(happy or unhappy?)',
    'happier': '_____(happier or unhappier?)',
    'harmful': '_____(beneficial or harmful?)',
    'has': '_____(has or doesn\'t have?)',
    'has been': '_____(has been or hasn\'t been?)',
    'hasn\'t been': '_____(has been or hasn\'t been?)',
    'has no': '_____(has or has no?)',
    'has not': '_____(has or hasn\'t?)',
    'have': '_____(have or don\'t have?)',
    'have been': '_____(have been or haven\'t been?)',
    'haven\'t been': '_____(have been or haven\'t been?)',
    'have no': '_____(have or have no?)',
    'have not': '_____(have or haven\'t?)',
    'high': '_____(high or low?)',
    'higher': '_____(higher or lower?)',
    'huge': '_____(size)',
    'immediate': '_____(graduate or immediate?)',
    'immediately': '_____(graduately or immediately?)',
    'impossible': '_____(possible or impossible?)',
    'increase': '_____(increase or decrease?)',
    'increases': '_____(increases or decreases?)',
    'is no': '_____(is or is no?)',
    'is not': '_____(is or isn\'t?)',
    'is': '_____(is or isn\'t?)',
    'isn\'t': '_____(is or isn\'t?)',
    'large': '_____(size)',
    'late': '_____(early or late?)',
    'later': '_____(earlier or later?)',
    'less': '_____(more or less?)',
    'long': '_____(long or short?)',
    'longer': '_____(longer or shorter?)',
    'low': '_____(high or low?)',
    'lower': '_____(higher or lower?)',
    'massive': '_____(size)',
    'may': '_____(may or may not?)',
    'may not': '_____(may or may not?)',
    'more': '_____(more or less?)',
    'must not': '_____(can or must not?)',
    'must': '_____(must or don\'t have to?)',
    'mustn\'t': '_____(can or must not?)',
    'need': '_____(need or don\'t need?)',
    'negative': '_____(positive or negative?)',
    'negatively': '_____(positively or negatively?)',
    'never': '_____(always or never?)',
    'new': '_____(old or new?)',
    'newer': '_____(older or newer?)',
    'old': '_____(old or new?)',
    'older': '_____(older or newer?)',
    'overestimate': '_____(underestimate or overestimate?)',
    'positive': '_____(positive or negative?)',
    'positively': '_____(positively or negatively?)',
    'possible': '_____(possible or impossible?)',
    'relative': '_____(absolute or relative?)',
    'short': '_____(long or short?)',
    'shorter': '_____(longer or shorter?)',
    'should not': '_____(should or shouldn\'t?)',
    'should': '_____(should or shouldn\'t?)',
    'shouldn\'t': '_____(should or shouldn\'t?)',
    'slow': '_____(fast or slow?)',
    'slower': '_____(faster or slower?)',
    'small': '_____(size)',
    'strong': '_____(strong or weak?)',
    'stronger': '_____(stronger or weaker?)',
    'strongest': '_____(strongest or weakest?)',
    'successful': '_____(successful or unsuccessful?)',
    'tiny': '_____(size)',
    'underestimate': '_____(underestimate or overestimate?)',
    'unhappy': '_____(happy or unhappy?)',
    'unhappier': '_____(happier or unhappier?)',
    'unsuccessful': '_____(successful or unsuccessful?)',
    'use': '_____(avoid or use?)',
    'weak': '_____(strong or weak?)',
    'weaker': '_____(stronger or weaker?)',
    'weakest': '_____(strongest or weakest?)',
    'will': '_____(will or won\'t?)',
    'with': '_____(with or without?)',
    'without': '_____(with or without?)',
    'won\'t': '_____(will or won\'t?)',
}
