GAP_SPECIAL_CASES = {
    'always': '_____(always or never?)',
    'are no': '_____(are or are no?)',
    'are not': '_____(are or aren\'t?)',
    'are': '_____(are or aren\'t?)',
    'aren\'t': '_____(are or aren\'t?)',
    'bad': '_____(good or bad?)',
    'big': '_____(size)',
    'can': '_____(can or can\'t?)',
    'can\'t': '_____(can or can\'t?)',
    'cannot': '_____(can or can\'t?)',
    'do not have to': '_____(must or don\'t have to?)',
    'do not have': '_____(have or don\'t have?)',
    'do not': '_____(do or don\'t?)',
    'do': '_____(do or don\'t?)',
    'does not have to': '_____(must or doesn\'t have to?)',
    'does not have': '_____(has or doesn\'t have?)',
    'does not': '_____(does or doesn\'t?)',
    'does': '_____(does or doesn\'t?)',
    'doesn\'t have to': '_____(must or doesn\'t have to?)',
    'doesn\'t have': '_____(has or doesn\'t have?)',
    'doesn\'t need': '_____(need or doesn\'t need?)',
    'doesn\'t': '_____(does or doesn\'t?)',
    'don\'t have to': '_____(must or don\'t have to?)',
    'don\'t have': '_____(have or don\'t have?)',
    'don\'t need': '_____(need or don\'t need?)',
    'don\'t': '_____(do or don\'t?)',
    'fast': '_____(fast or slow?)',
    'faster': '_____(faster or slower?)',
    'good': '_____(good or bad?)',
    'graduate': '_____(graduate or immediate?)',
    'graduately': '_____(graduately or immediately?)',
    'has no': '_____(has or has no?)',
    'has': '_____(has or doesn\'t have?)',
    'have no': '_____(have or have no?)',
    'have': '_____(have or don\'t have?)',
    'high': '_____(high or low?)',
    'higher': '_____(higher or lower?)',
    'huge': '_____(size)',
    'immediate': '_____(graduate or immediate?)',
    'immediately': '_____(graduately or immediately?)',
    'impossible': '_____(possible or impossible?)',
    'is no': '_____(is or is no?)',
    'is not': '_____(is or isn\'t?)',
    'is': '_____(is or isn\'t?)',
    'isn\'t': '_____(is or isn\'t?)',
    'large': '_____(size)',
    'less': '_____(more or less?)',
    'long': '_____(long or short?)',
    'longer': '_____(longer or shorter?)',
    'low': '_____(high or low?)',
    'lower': '_____(higher or lower?)',
    'massive': '_____(size)',
    'more': '_____(more or less?)',
    'must not': '_____(can or must not?)',
    'must': '_____(must or don\'t have to?)',
    'mustn\'t': '_____(can or must not?)',
    'need': '_____(need or don\'t need?)',
    'never': '_____(always or never?)',
    'new': '_____(old or new?)',
    'newer': '_____(older or newer?)',
    'old': '_____(old or new?)',
    'older': '_____(older or newer?)',
    'possible': '_____(possible or impossible?)',
    'short': '_____(long or short?)',
    'shorter': '_____(longer or shorter?)',
    'should not': '_____(should or shouldn\'t?)',
    'should': '_____(should or shouldn\'t?)',
    'shouldn\'t': '_____(should or shouldn\'t?)',
    'slow': '_____(fast or slow?)',
    'slower': '_____(faster or slower?)',
    'small': '_____(size)',
    'tiny': '_____(size)',
    'will': '_____(will or won\'t?)',
    'with': '_____(with or without?)',
    'without': '_____(with or without?)',
    'won\'t': '_____(will or won\'t?)',
}
